In [1]:
import numpy as np


In [2]:
n = 100 

shuffled_indices = np.random.permutation(n)

In [3]:
shuffled_indices

array([41, 31,  7, 23, 36, 60, 43, 81, 57, 83, 80, 50, 16, 67, 37, 21, 53,
       42, 75, 89,  9, 51, 32, 25, 45, 71, 22, 33,  5, 40, 61, 87, 30, 82,
       77, 39, 49, 17,  3, 28, 20, 93, 48,  2, 27, 62, 59, 38, 97, 14, 55,
       85, 64, 24, 47, 11, 90, 66, 86, 65, 84,  1, 73, 29, 19, 72, 44, 34,
       88, 58, 18, 63, 10, 94, 78, 76,  0, 69, 12, 13, 98, 56, 68, 95, 70,
       91, 54, 35, 79, 52, 46, 15, 96, 99, 92,  6,  8,  4, 26, 74])

In [4]:
test_indices = shuffled_indices[20:40]
train_indices = shuffled_indices[]

In [5]:
test_indices

array([41, 31,  7, 23, 36, 60, 43, 81, 57, 83, 80, 50, 16, 67, 37, 21, 53,
       42, 75, 89])

In [6]:
train_indices

array([ 9, 51, 32, 25, 45, 71, 22, 33,  5, 40, 61, 87, 30, 82, 77, 39, 49,
       17,  3, 28, 20, 93, 48,  2, 27, 62, 59, 38, 97, 14, 55, 85, 64, 24,
       47, 11, 90, 66, 86, 65, 84,  1, 73, 29, 19, 72, 44, 34, 88, 58, 18,
       63, 10, 94, 78, 76,  0, 69, 12, 13, 98, 56, 68, 95, 70, 91, 54, 35,
       79, 52, 46, 15, 96, 99, 92,  6,  8,  4, 26, 74])