In [1]:
import numpy as np

arr = np.array([1, 3, 5])

arr

array([1, 3, 5])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.empty(3)

array([0., 0., 0.])

In [5]:
np.arange(4)

array([0, 1, 2, 3])

In [6]:
list(range(4))

[0, 1, 2, 3]

## Indexing and Slicing

In [7]:
import numpy as np

data = np.array([1, 3, 5, 7, 9])

In [8]:
len(data)

5

In [9]:
data[1:3]

array([3, 5])

In [10]:
data[1:]

array([3, 5, 7, 9])

In [13]:
data[-2:]

array([7, 9])

## Operations

In [16]:
data_1 = [1, 2, 3]
data_2 = [11, 21, 31]

data_1, data_2 = np.array(data_1), np.array(data_2)

data_1 + data_2

array([12, 23, 34])

Broadcasting

In [18]:
dist = np.array([1, 2, 3]) # unit is mile
distInKm = dist * 1.6

distInKm

array([1.6, 3.2, 4.8])

# Broadcasting and conditions

In [19]:
data = [-1, 2, -4, 0, 3, 100, -5]

postive_numbers = filter(lambda x: x>0, data)

list(postive_numbers)

[2, 3, 100]

In [21]:
data = [-1, 2, -4, 0, 3, 100, -5]
data = np.array(data)

data[data > 0]


array([  2,   3, 100])

In [23]:
# odd numbers
data = [-1, 2, -4, 0, 3, 100, -5]
data = np.array(data)

data[data%2 != 0]


array([-1,  3, -5])

## Statistical calculations

In [24]:
data = np.array([23, 2, 9, 8, 54, 89, 23])

data.sum()

208

In [25]:
data.min(), data.max(), data.mean(), data.std()

(2, 89, 29.714285714285715, 28.941884062051393)

## Matrix

In [27]:
m = [ [1, 2], [3, 4], [5, 6], [7, 8] ]

m = np.array(m)
m

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
m[:,1]

array([2, 4, 6, 8])

In [33]:
m[1,:]

array([3, 4])