In [2]:
import numpy as np 
a = np.array([1,4,5])
print(a)

[1 4 5]


#set tuple and dictionary


s={1,2, "RBS"}


In [4]:
len(a)


3

In [7]:
universities = {'Princeton', 'NYU','Rutgers'}
'Rutgers' in universities

True

In [ ]:
# shift + enter = new codspace

In [8]:
l = [ 1, 2, 3]
s= set(l)
s

{1, 2, 3}

In [14]:
s1 = {1,2}
s2 = {6,7}
inter = s1.intersection(s2)
inter
all = s1.union(s2)
all
diff = s1.difference(s2) # in s2, but not in s2
print('inter',inter)
print('all',all)
print('diff', diff)

inter set()
all {1, 2, 6, 7}
diff {1, 2}


#Tuple

In [18]:
t = 'a', 'b', 'c', 'd' # or t = ('a', 'b', 'c', 'd')
t[1]

'b'

In [23]:
def get_quot_rem(x, y):
  return x//y, x%y
x, y = 7, 3
quot, rem = get_quot_rem(x, y)
#  , rem = 1

get_quot_rem(x,y)
printquot
rem

2

In [24]:
quot

2

In [25]:
rem

1

In [27]:
counties = ['MIDDLESEX', 'MIDDLESEX', 'SOMERSET']
cities = ['Piscataway', 'HIGHLAND PARK', 'FLAGTOWN']
zipcodes = ['08854', '08904', '08821']
print(list(zip(counties, cities, zipcodes)))



[('MIDDLESEX', 'Piscataway', '08854'), ('MIDDLESEX', 'HIGHLAND PARK', '08904'), ('SOMERSET', 'FLAGTOWN', '08821')]


enumerate() function

In [29]:
universities = ["Princeton", "MIT", "Harvard", "Stanford"]
for i, university in enumerate(universities):
  print(i+1, university)
print(list(enumerate(universities)))

1 Princeton
2 MIT
3 Harvard
4 Stanford
[(0, 'Princeton'), (1, 'MIT'), (2, 'Harvard'), (3, 'Stanford')]


# Dictionary

In [30]:
eng2arabic = {'one':1, 'two':2, 'three':3}
eng2arabic

{'one': 1, 'two': 2, 'three': 3}

In [31]:
eng2arabic ['four'] = 4
eng2arabic

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

In [33]:
d = dict()
d['one']=1
d['two']=2
d

{'one': 1, 'two': 2}

In [35]:
# key and value

# in for key not for value
1 in d.values() ###************

True

# Dictionary and list

In [36]:
cities = ['PISCATAWAY', 'HIGHLAND PARK', 'FLAGTOWN']
zipcodes = ['08854', '08904', '08821']
d = dict(zip(cities, zipcodes))
d

{'PISCATAWAY': '08854', 'HIGHLAND PARK': '08904', 'FLAGTOWN': '08821'}

In [2]:
import numpy as np 
arr = np.array([1,3,5])
arr

array([1, 3, 5])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.empty(4)

array([2.12199579e-314, 8.21212371e-312, 3.85371204e-321, 6.95272004e-310])

In [5]:
np.empty(3)

array([8.21262933e-312, 0.00000000e+000, 2.41907520e-312])

In [6]:
np.arange(5)


array([0, 1, 2, 3, 4])

# Indexing and Slicing


In [7]:
import numpy as np
data_1 = [1, 2, 3]
data_2 = [11, 21, 31]
data_1, data_2 = np.array(data_1), np.array(data_2)

print(data_1 + data_2)
print(data_1 - data_2)
print(data_1 * data_2)

[12 23 34]
[-10 -19 -28]
[11 42 93]


# Operations => Broadcasting

In [10]:
dist = np.array([1,2,3]) #unit is mile
disInKm = dist * 1.6
disInKm

array([1.6, 3.2, 4.8])

In [11]:
data = [-1, 1, -2, 0, 4,-4 ]
pos =filter(lambda x: x>0, data)


In [12]:
# Statistical

# Statistical

In [18]:
data= np.array([1,2,3,-1])
data.sum()
data.min()
data.max()
data.mean()
data.std()


1.479019945774904

In [20]:
n = [ [1,2], [3,4]] #m[:,1] colummn
n = np.array(n)
n[:,1]

array([2, 4])

# Panda

In [24]:
import pandas as pd # panda just like series
import numpy as np
l = [10, 12, 2]

s = pd.Series(l) #s = pd.Series(l, index['a','b'])
s
n =np.array(l)
n

array([10, 12,  2])

# from dictionary

In [25]:
d = {'Nan':90, 'Abot':20}
pd.Series(d)

Nan     90
Abot    20
dtype: int64

# series id ndarray like

In [26]:
np.log(l)

array([2.30258509, 2.48490665, 0.69314718])

# indexing and slicing

In [29]:
l = [10, 12, 2]
s.iloc[1]
s.iloc[-2:]

1    12
2     2
dtype: int64

# Dataframe

In [31]:
d= {"one": pd.Series([10,11,12], index=['a','b','c']),
"two":pd.Series([1.2,2.2,2.6])}
df = pd.DataFrame(d)
df


SyntaxError: ':' expected after dictionary key (2596995588.py, line 1)

In [30]:
d= {"one": pd.Series([10,11,12]),
"two":pd.Series([1.2,2.2,2.6])}
df = pd.DataFrame(d)
df

one  two
0   10  1.2
1   11  2.2
2   12  2.6